### ISSUE TITLE
Have an option to always the reserve bottom lines of the terminal for the completion menu.

### ISSUE THREAD

**Issue by jonathanslenders** [jonathanslenders/python-prompt-toolkit#149]
For ``prompt_toolkit.shortcuts.create_default_layout``, currently the input scrolls up when the completion menu is displayed. But only if no bottom toolbar is displayed.

The reason is that the printing the bottom toolbar requires the terminal to scroll up. But if there is no visible output below the actual input, we don't send anything to the renderer/output classes to make this happen.

cc: @melund

**Comment by jonathanslenders** [comment]
Fixed: https://github.com/jonathanslenders/python-prompt-toolkit/commit/031edabbb719d11d70165f82a281aa421427e7df

**Comment by melund** [comment]
@jonathanslenders . I tried to test this. It no longer scrolls up just as I hit tab, but the problem is still the same. Now scrolling just happens just when a command is executed. It can best be examplained with a video.

[![ScreenShot](https://cloud.githubusercontent.com/assets/1038978/9493195/4a4e4b40-4bfe-11e5-9332-10b131d448fd.png)](https://youtu.be/61tEgbNKTmM)

Btw. When I press tab at the start of a line. It actually inserts the tab characters as well as opening the completion box. (see the end of the video). Any idea if this is due to xonsh or prompt_toolkit?
