### ISSUE TITLE
Long multiline inputs are getting their tops shaved off

### ISSUE THREAD

**Issue by gforsyth** [jonathanslenders/python-prompt-toolkit#254]
This was first noticed by @melund in scopatz/xonsh#703

in `xonsh` master using the `prompt_toolkit` shell (version 0.58) lines that exceed the prompt width wrap (as expected) but then on execution the top 1 or 2 lines disappears

![](https://cloud.githubusercontent.com/assets/1038978/13353473/f6578fec-dc94-11e5-8fe7-681972bb5104.png)

![](https://cloud.githubusercontent.com/assets/1038978/13353525/563961f6-dc95-11e5-8924-d568510081ae.png)

The same is true if a long input is put in a tiny terminal in `examples/get-multiline-input.py`

![2016-02-26-094752_447x594_escrotum](https://cloud.githubusercontent.com/assets/3596999/13355484/a8026450-dc6e-11e5-989a-813cfdf4b90a.png)
![2016-02-26-094800_447x594_escrotum](https://cloud.githubusercontent.com/assets/3596999/13355485/a8049842-dc6e-11e5-94cb-5c158572c4e9.png)

**Comment by jonathanslenders** [comment]
Thanks for reporting @gforsyth,
This is clearly a bug. I'll fix it asap (probably not before Sunday, unfortunately), but then I'll do a new release.

**Comment by jonathanslenders** [comment]
Hi @gforsyth,

This commit should probably fix it: https://github.com/jonathanslenders/python-prompt-toolkit/commit/0c3b0c7a721bf33c8e92bf6b351cb8879924f0b2

Can you have a try? (with the latest master version.)
I will also do a bit more testing, and if everything is fine, then I will push a new release for this.
Jonathan

**Comment by gforsyth** [comment]
Hey @jonathanslenders -- that has fixed the lines being shaved, but seems to have introduced a different bug (or I just noticed this after the fact).  If I reduce the width of my terminal window such that it covers even 1 character of the `$PROMPT` title, the instance crashes with this traceback

```Python
Traceback (most recent call last):
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/controls.py", line 141, in get_height_for_line
KeyError: (0, 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/interface.py", line 353, in run
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/eventloop/posix.py", line 150, in run
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/eventloop/posix.py", line 197, in process_winch
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/interface.py", line 831, in terminal_size_changed
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/interface.py", line 325, in _on_resize
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/interface.py", line 313, in _redraw
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/renderer.py", line 420, in render
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 141, in write_to_screen
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 176, in _divide_heigths
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 176, in <listcomp>
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 174, in get_dimension_for_child
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 394, in preferred_height
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 971, in preferred_height
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/controls.py", line 485, in preferred_height
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/controls.py", line 144, in get_height_for_line
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/controls.py", line 156, in get_height_for_text
ZeroDivisionError: integer division or modulo by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/controls.py", line 141, in get_height_for_line
KeyError: (0, 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gil/anaconda/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.6', 'console_scripts', 'xonsh')()
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/main.py", line 212, in main
    shell.cmdloop()
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 111, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 80, in singleline
    display_completions_in_columns=multicolumn)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/ptk/shortcuts.py", line 102, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/interface.py", line 363, in run
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/interface.py", line 313, in _redraw
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/renderer.py", line 420, in render
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 141, in write_to_screen
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 176, in _divide_heigths
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 176, in <listcomp>
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 174, in get_dimension_for_child
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 394, in preferred_height
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/containers.py", line 971, in preferred_height
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/controls.py", line 485, in preferred_height
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/controls.py", line 144, in get_height_for_line
  File "/home/gil/anaconda/lib/python3.5/site-packages/prompt_toolkit-0.58-py3.5.egg/prompt_toolkit/layout/controls.py", line 156, in get_height_for_text
ZeroDivisionError: integer division or modulo by zero
```

**Comment by jonathanslenders** [comment]
That's a different bug. Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/39b34aa6279e3f146b58927e4d0c5bb36bdf1565

Sorry about this! Can you please test again? If everything is fine now, I will push a new release.

**Comment by gforsyth** [comment]
Hey @jonathanslenders, thanks!  Everything is working now on my end.

**Comment by gforsyth** [comment]
Resolved in 0c3b0c7

**Comment by jonathanslenders** [comment]
0.99 has been pushed to Pypi.

Still having some issues pushing the Python 3 wheels. (These are slightly bigger and bad internet connection at the moment. But I'll try again.)
