### ISSUE TITLE
Not all completions are shown

### ISSUE THREAD

**Issue by melund** [jonathanslenders/python-prompt-toolkit#320]
We have seen a problem with xonsh where the completer would not show all completions and left out quoted path names with spaces in the name. 

https://github.com/xonsh/xonsh/issues/1201#issuecomment-225485796

Since the  xonsh completer does find all the right paths we were thinking that this may be an issue with prompt-toolkit. I remember that this used to work.

**Comment by jonathanslenders** [comment]
Hi @melund,

Thanks a lot for reporting this bug! The following commit should fix it: https://github.com/jonathanslenders/python-prompt-toolkit/commit/5f073ff3f91ffb9e7db0a54d57403a86e0035064

Could you please test again with the latest master branch of prompt-toolkit?

Thanks,
Jonathan

**Comment by melund** [comment]
It didn't seem to have any effect: 

![image](https://cloud.githubusercontent.com/assets/1038978/16080471/515c47fa-3309-11e6-8646-215e3926c97e.png)

![image](https://cloud.githubusercontent.com/assets/1038978/16080483/5de8289a-3309-11e6-8573-812988460011.png)

**Comment by adqm** [comment]
@jonathanslenders, @melund: is ptk expecting all of the completions to start with the same prefix?  If so, we can fix this on xonsh's end by adding quotes to _all_ completions if we add them to any.

**Comment by melund** [comment]
Ahhh. That is it. A quick hack to `completers/path.py` confirmed that this is indeed the case.

**Comment by melund** [comment]
I will try to make a fix if it is OK with you :)

**Comment by melund** [comment]
Ok. I made a fix for this in xonsh. https://github.com/xonsh/xonsh/pull/1244

@jonathanslenders ... I am sorry for the noise if it was our problem all along.

**Comment by jonathanslenders** [comment]
@adqm: Completions don't have to start with the same prefix.

Today I released a new version of prompt-toolkit 1.0.1 with the above fix. (There was also one issue related to this on our side.) Let me know whether there are still some issues or whether it's fixed now.

**Comment by gforsyth** [comment]
hey @jonathanslenders -- thanks as always for all the help!  

on current master I'm still seeing the following behavior:

I have a directory as follows:
```console
tmp/
  ˫ 1/
  ˫ 2/
  ˫ 3 and 4/
```

The set of completions that `xonsh` generates for this is `{"'3 and 4/'", '1/', '2/'}` but the completions displayed are `./`, `../`, `1/`, `2/` only.

**Comment by gforsyth** [comment]
Ack.  Sorry for the noise, @jonathanslenders -- @melund just fixed this on our end.

**Comment by adqm** [comment]
FTR, though, it seems like the fix in ptk did make a difference as well (the fix on our end is specific to completing lines starting with `cd` or `rmdir`, whereas this fixed completions for other commands).

**Comment by jonathanslenders** [comment]
@adqm: Thanks for sharing!
