### ISSUE TITLE
Cannot focus DynamicContainer

### ISSUE THREAD

**Issue by lostatc** [jonathanslenders/python-prompt-toolkit#707]
I would like to have the contents of a container update based on what is focused. I figured that using a `DynamicContainer` was the best way to achieve this. However, whenever I put a normally focusable widget in a `DynamicContainer`, it seems to be impossible to focus it. Here's an example:

```python
bindings = KeyBindings()
bindings.add("c-c")(lambda event: event.app.exit())
bindings.add("tab")(focus_next)
bindings.add("s-tab")(focus_previous)

regular_button = Button("Regular")
dynamic_button = DynamicContainer(lambda: Button("Dynamic"))

layout = Layout(
    HSplit([
        regular_button,
        dynamic_button,
    ]),
)

app = Application(layout=layout, key_bindings=bindings)
app.run()
```

In this example, I can focus `regular_button` but not `dynamic_button`. If I try to focus it using `layout.focus(dynamic_button)`, I get the following stack trace:

```
Traceback (most recent call last):
  File "/home/garrett/.PyCharm2018.2/config/scratches/scratch_39.py", line 24, in <module>
    layout.focus(dynamic_button)
  File "/home/garrett/.local/share/virtualenvs/skiddie-x-macEj3/lib/python3.5/site-packages/prompt_toolkit/layout/layout.py", line 141, in focus
    raise ValueError('Invalid value. Container cannot be focused: %r' % (value, ))
ValueError: Invalid value. Container cannot be focused: <prompt_toolkit.layout.containers.DynamicContainer object at 0x7f725252e780>
```

If this is intended behavior, I would really appreciate it if anyone could let me know of another way to achieve what I'm trying to do.

Thanks,
Garrett

**Comment by jonathanslenders** [comment]
Hi @lostatc,
I think this was solved in the following commit: ea93753ba6eaae23f8fac7f94c91f74d587155a5
Can you try to check out the master branch and try again?

**Comment by lostatc** [comment]
Thanks for the quick reply!

I tried my example using the master branch, and `layout.focus(dynamic_button)` no longer raises an exception. However, it still doesn't seem to be focusing the widget. `layout.has_focus(dynamic_button)` returns `False`, and the button doesn't have the selected style.

**Comment by jonathanslenders** [comment]
Hi @lostatc,

I noticed the problem is on the following line:
```python
dynamic_button = DynamicContainer(lambda: Button("Dynamic"))
```
This creates every a different button every single time. That doesn't work because ``focus_next`` first tries to enumerate all widgets that are focusable, then checks in that list what the current widget is, and goes to the next one. By that time, this button is already gone. If we would set this specific instance as the focused button, the renderer also wouldn't know where to find it.

Try to rewrite it as follows:
```python
button = Button("Dynamic")
dynamic_button = DynamicContainer(lambda: button)
```

Maybe, that's some thing that should be mentioned in the documentation of ``DynamicContainer``.

**Comment by lostatc** [comment]
Thank you for clarifying that.

I think I was misunderstanding the purpose of `DynamicContainer`. I was trying to use it to dynamically update the contents of a container by creating a new container with new contents. Instead, it looks like it's actually intended for dynamically switching between existing containers.

I'm trying to change the contents of a `TextArea` based on which button is focused. If I have ten buttons, is my best option to create ten `TextArea` instances and switch between them? Is there a way to just update the contents of one `TextArea` whenever the focus changes?

**Comment by jonathanslenders** [comment]
Hi @lostatc,

Right now, the ``Layout`` class doesn't define an event for ``on_focus``. You can work around that by inheriting from ``Layout`` and overriding the ``focus()`` method. However, I'd accept a pull request for this.

You can change the text of a ``TextArea`` by assigning to the ``.text`` property.

**Comment by lostatc** [comment]
Thanks for all the help @jonathanslenders! That answers my question. I'll go ahead and close this issue.
